In [1]:
import numpy as np
import pandas as pd

Array numpy

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
type(arr)

numpy.ndarray

In [8]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr[0]

1

In [12]:
arr[0] + arr[5]

7

In [14]:
matriz[0,2]

3

In [15]:
arr[0:3]

array([1, 2, 3])

In [16]:
arr[::3]

array([1, 4, 7])

In [18]:
arr[-1]

9

In [19]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

tipos de datos

In [30]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [31]:
arr

array([1, 2, 3, 4])

In [32]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [27]:
arr = np.array([1, 2, 3, 4], dtype='float64')
arr.dtype

dtype('float64')

In [36]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True])

In [37]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3'], dtype='|S21')

In [38]:
arr = np.array(['0', '1', '2', '3'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3], dtype=int8)

Dimensiones

In [39]:
scalar = np.array(42)
print(scalar)
print(scalar.ndim)

42
0


In [40]:
vector = np.array([1, 2, 3])
print(vector)
print(vector.ndim)

[1 2 3]
1


In [41]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
print(matriz.ndim)

[[1 2 3]
 [4 5 6]]
2


In [42]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)
print(tensor.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [44]:
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [47]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
print(expand.ndim)

[[1 2 3]]
2


In [48]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 10


creacion de arrays usando numpy puro

In [3]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((10, 10)) # crea una matriz con el tamanio entre la tupla, se puede pasar un valor scalar

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((10, 5)) # lo mismo que arriba pero con unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0, 10, 10)  # Crea una distribnucion normalizada

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

np.eye(4)  # Crea matriz unaria

In [11]:
np.random.rand() # Crea un valor aleatorio

0.8453166532603645

In [12]:
np.random.rand(4) # Crea valores aleatorios siendo el argumento el numero de elementos

array([0.95191114, 0.92481868, 0.69199288, 0.9501509 ])

In [14]:
np.random.rand(4, 4) # no encerrado en una tupla por que falla

array([[0.96571732, 0.57126819, 0.37885151, 0.00947404],
       [0.58046007, 0.87097695, 0.30801417, 0.00815299],
       [0.38686107, 0.79704186, 0.23777866, 0.20667061],
       [0.97665005, 0.61889905, 0.16894034, 0.76714826]])

In [15]:
np.random.randint(1, 15) # crea un valor de tipo int

11

In [17]:
np.random.randint(1, 100, (10, 5)) # Crea una matriz de 10x10

array([[17, 27, 48, 69, 42],
       [26, 20, 58, 10, 29],
       [30, 18, 40, 37, 25],
       [ 9, 10, 97, 44, 54],
       [53, 76,  4, 71, 87],
       [89, 32, 69, 60, 56],
       [ 9, 43, 84, 48, 88],
       [77,  4,  9, 40, 39],
       [69, 96, 47, 36, 54],
       [21, 42,  3, 33, 64]])

Shape and reshape

In [19]:
arr = np.random.randint(1, 10, (3, 2))

In [20]:
arr.shape

(3, 2)

In [22]:
arr

array([[4, 5],
       [9, 1],
       [4, 3]])

In [21]:
arr.reshape(1, 6)

array([[4, 5, 9, 1, 4, 3]])

In [23]:
arr.reshape(2, 3)

array([[4, 5, 9],
       [1, 4, 3]])

In [24]:
np.reshape(arr, (1, 6))

array([[4, 5, 9, 1, 4, 3]])

In [26]:
arr

array([[4, 5],
       [9, 1],
       [4, 3]])

In [27]:
np.reshape(arr, (2, 3), 'C')

array([[4, 5, 9],
       [1, 4, 3]])

In [28]:
np.reshape(arr, (2, 3), 'F')

array([[4, 4, 1],
       [9, 5, 3]])

In [29]:
np.reshape(arr, (2, 3), 'A')

array([[4, 5, 9],
       [1, 4, 3]])

Funciones principales

In [32]:
arr = np.random.randint(1, 20, 10)
arr

array([ 3, 12, 18,  9, 17, 10,  8, 18,  7, 18])

In [33]:
matriz = arr.reshape(2, 5)
matriz

array([[ 3, 12, 18,  9, 17],
       [10,  8, 18,  7, 18]])

In [34]:
arr.max()  # numero mas grande en el array

18

In [37]:
matriz.max(0) # el argumento sabe para encontrar el valor por eje

array([10, 12, 18,  9, 18])

In [38]:
arr.argmax()

2

In [40]:
matriz.argmax(0)

array([1, 0, 0, 0, 1])

In [41]:
arr.min()

3

In [43]:
matriz.min(0)

array([ 3,  8, 18,  7, 17])

In [44]:
arr.argmin()

0

In [45]:
matriz.argmin(0)

array([0, 1, 0, 1, 0])

In [46]:
arr.ptp() # del pico mas bajo al mas alto cual es la diferencia

15

In [49]:
matriz.ptp(0)

array([7, 4, 0, 2, 1])

In [51]:
np.percentile(arr, 50)

11.0

In [53]:
arr.sort()
arr

array([ 3,  7,  8,  9, 10, 12, 17, 18, 18, 18])

In [54]:
np.median(arr)

11.0

In [55]:
np.median(matriz, 0)

array([ 7.5, 12. , 13. , 13.5, 14. ])

In [56]:
np.std(arr)

5.176871642217914

In [57]:
np.var(arr)

26.8

In [58]:
np.mean(arr)

12.0

In [59]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [65]:
b = np.array([4, 6])
b

array([4, 6])

In [66]:
b = np.expand_dims(b, axis=0)
np.concatenate((a, b), 0) # Fallan por ser de diferente dimension

array([[1, 2],
       [3, 4],
       [4, 6]])

In [68]:
np.concatenate((a, b.T), 1)

array([[1, 2, 4],
       [3, 4, 6]])

Copy

In [69]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
trozo_de_arr = arr[0:6] # No es como python normal donde se hace la copia directa

In [72]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [73]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [77]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [78]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [79]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Condiciones

In [81]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [83]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [86]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

Operaciones

In [87]:
lista = [1, 2]
lista

[1, 2]

In [88]:
lista * 2

[1, 2, 1, 2]

In [90]:
arr = np.arange(0, 10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [92]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
1 / arr

/tmp/ipykernel_112113/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [94]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [95]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [97]:
matriz = arr.reshape(2, 5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [98]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [99]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [104]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [105]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

Pandas

In [2]:
series = pd.Series(['uno', 'dos', 'tres', 'cuatro'], index=[1, 7, 10, 30])
series

1        uno
7        dos
10      tres
30    cuatro
dtype: object

In [3]:
pd.Series(['uno', 'dos', 'tres', 'cuatro'])

0       uno
1       dos
2      tres
3    cuatro
dtype: object

In [4]:
dictionary = {1: 'uno', 7: 'siete', 10: 'diez', 30: 'tre'}
pd.Series(dictionary)

1       uno
7     siete
10     diez
30      tre
dtype: object

In [5]:
series[7]

'dos'

In [6]:
dictionary = {'numero': ['uno', 'dos', 'tres', 'cuatro'], 'valor': [1, 2, 3, 4], 'rel': [0, 1, 2, 3]}

In [8]:
df = pd.DataFrame(dictionary)

In [9]:
df.columns, df.index

(Index(['numero', 'valor', 'rel'], dtype='object'),
 RangeIndex(start=0, stop=4, step=1))

In [11]:
df = pd.read_csv('bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [13]:
pd.read_json('hpcharactersdataraw_3d934e85-dfa4-42ec-8520-fadfbecae574.json', typ='Series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

In [14]:
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [15]:
df[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [18]:
df[['Name', 'Author', 'Year']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  Year  
0                    JJ Smith  2016  
1                Stephen King  2011  
2          Jordan B. Peterson  2018  
3               George Orwell  2017  
4    National Geographic Kids  2019  
..                        ...   ...  
545               Jeff Kinney  2019  
546               Jen Sincero  2016  
547               Jen Sincero  2017  
548               Jen Sincero  2018  
549               Jen Sincero  2019  

[550 rows x 3 columns]

In [19]:
df.loc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [21]:
df.loc[0:4, ['Name', 'Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [23]:
df.loc[:, ['Reviews']] * -1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [24]:
df.loc[:, ['Author']] == 'JJ Smith'

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

In [26]:
df.iloc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [28]:
df.iloc[:,0:3]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

In [29]:
df.iloc[1,3] * -1

-2052