In [1]:
import numpy as np
import pandas as pd

Array numpy

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(arr)

numpy.ndarray

In [4]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[0]

1

In [6]:
arr[0] + arr[5]

7

In [7]:
matriz[0,2]

3

In [8]:
arr[0:3]

array([1, 2, 3])

In [9]:
arr[::3]

array([1, 4, 7])

In [10]:
arr[-1]

9

In [11]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [12]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

tipos de datos

In [13]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [14]:
arr

array([1, 2, 3, 4])

In [15]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [16]:
arr = np.array([1, 2, 3, 4], dtype='float64')
arr.dtype

dtype('float64')

In [17]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True])

In [18]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3'], dtype='|S21')

In [19]:
arr = np.array(['0', '1', '2', '3'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3], dtype=int8)

Dimensiones

In [20]:
scalar = np.array(42)
print(scalar)
print(scalar.ndim)

42
0


In [21]:
vector = np.array([1, 2, 3])
print(vector)
print(vector.ndim)

[1 2 3]
1


In [22]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
print(matriz.ndim)

[[1 2 3]
 [4 5 6]]
2


In [23]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)
print(tensor.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [24]:
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [25]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
print(expand.ndim)

[[1 2 3]]
2


In [26]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 10


creacion de arrays usando numpy puro

In [27]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.zeros((10, 10)) # crea una matriz con el tamanio entre la tupla, se puede pasar un valor scalar

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.ones((10, 5)) # lo mismo que arriba pero con unos

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.linspace(0, 10, 10)  # Crea una distribnucion normalizada

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

np.eye(4)  # Crea matriz unaria

In [31]:
np.random.rand() # Crea un valor aleatorio

0.8746415289891802

In [32]:
np.random.rand(4) # Crea valores aleatorios siendo el argumento el numero de elementos

array([0.1298604 , 0.37302815, 0.17089939, 0.03591964])

In [33]:
np.random.rand(4, 4) # no encerrado en una tupla por que falla

array([[0.2060188 , 0.86537985, 0.7977069 , 0.92829338],
       [0.46070919, 0.65978301, 0.34877585, 0.64775792],
       [0.99683989, 0.64662508, 0.56758076, 0.44370057],
       [0.60297606, 0.84932533, 0.35331112, 0.6812541 ]])

In [34]:
np.random.randint(1, 15) # crea un valor de tipo int

14

In [35]:
np.random.randint(1, 100, (10, 5)) # Crea una matriz de 10x10

array([[62, 77, 98, 19, 79],
       [60, 21, 56, 34, 28],
       [73,  6, 77, 49, 20],
       [64, 89, 63, 33, 88],
       [51, 30, 67, 71, 47],
       [34, 54, 24, 54, 87],
       [79, 51, 91, 39, 75],
       [60, 56, 93,  1,  9],
       [32, 91, 80, 58, 17],
       [98, 37, 82, 62, 99]])

Shape and reshape

In [36]:
arr = np.random.randint(1, 10, (3, 2))

In [37]:
arr.shape

(3, 2)

In [38]:
arr

array([[9, 6],
       [6, 9],
       [6, 2]])

In [39]:
arr.reshape(1, 6)

array([[9, 6, 6, 9, 6, 2]])

In [40]:
arr.reshape(2, 3)

array([[9, 6, 6],
       [9, 6, 2]])

In [41]:
np.reshape(arr, (1, 6))

array([[9, 6, 6, 9, 6, 2]])

In [42]:
arr

array([[9, 6],
       [6, 9],
       [6, 2]])

In [43]:
np.reshape(arr, (2, 3), 'C')

array([[9, 6, 6],
       [9, 6, 2]])

In [44]:
np.reshape(arr, (2, 3), 'F')

array([[9, 6, 9],
       [6, 6, 2]])

In [45]:
np.reshape(arr, (2, 3), 'A')

array([[9, 6, 6],
       [9, 6, 2]])

Funciones principales

In [46]:
arr = np.random.randint(1, 20, 10)
arr

array([ 1, 14, 18,  9, 18,  3, 16,  7,  5, 17])

In [47]:
matriz = arr.reshape(2, 5)
matriz

array([[ 1, 14, 18,  9, 18],
       [ 3, 16,  7,  5, 17]])

In [48]:
arr.max()  # numero mas grande en el array

18

In [49]:
matriz.max(0) # el argumento sabe para encontrar el valor por eje

array([ 3, 16, 18,  9, 18])

In [50]:
arr.argmax()

2

In [51]:
matriz.argmax(0)

array([1, 1, 0, 0, 0])

In [52]:
arr.min()

1

In [53]:
matriz.min(0)

array([ 1, 14,  7,  5, 17])

In [54]:
arr.argmin()

0

In [55]:
matriz.argmin(0)

array([0, 0, 1, 1, 1])

In [56]:
arr.ptp() # del pico mas bajo al mas alto cual es la diferencia

17

In [57]:
matriz.ptp(0)

array([ 2,  2, 11,  4,  1])

In [58]:
np.percentile(arr, 50)

11.5

In [59]:
arr.sort()
arr

array([ 1,  3,  5,  7,  9, 14, 16, 17, 18, 18])

In [60]:
np.median(arr)

11.5

In [61]:
np.median(matriz, 0)

array([ 7.5,  9.5, 11. , 12.5, 13.5])

In [62]:
np.std(arr)

6.2257529665093525

In [63]:
np.var(arr)

38.76

In [64]:
np.mean(arr)

10.8

In [65]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [66]:
b = np.array([4, 6])
b

array([4, 6])

In [67]:
b = np.expand_dims(b, axis=0)
np.concatenate((a, b), 0) # Fallan por ser de diferente dimension

array([[1, 2],
       [3, 4],
       [4, 6]])

In [68]:
np.concatenate((a, b.T), 1)

array([[1, 2, 4],
       [3, 4, 6]])

Copy

In [69]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
trozo_de_arr = arr[0:6] # No es como python normal donde se hace la copia directa

In [71]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [72]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [73]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [74]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [75]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

Condiciones

In [76]:
arr = np.linspace(1, 10, 10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [77]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [78]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

Operaciones

In [79]:
lista = [1, 2]
lista

[1, 2]

In [80]:
lista * 2

[1, 2, 1, 2]

In [81]:
arr = np.arange(0, 10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [83]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
1 / arr

/tmp/ipykernel_64574/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [85]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [86]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
matriz = arr.reshape(2, 5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [89]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [90]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [91]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

Pandas

In [92]:
series = pd.Series(['uno', 'dos', 'tres', 'cuatro'], index=[1, 7, 10, 30])
series

1        uno
7        dos
10      tres
30    cuatro
dtype: object

In [93]:
pd.Series(['uno', 'dos', 'tres', 'cuatro'])

0       uno
1       dos
2      tres
3    cuatro
dtype: object

In [94]:
dictionary = {1: 'uno', 7: 'siete', 10: 'diez', 30: 'tre'}
pd.Series(dictionary)

1       uno
7     siete
10     diez
30      tre
dtype: object

In [95]:
series[7]

'dos'

In [96]:
dictionary = {'numero': ['uno', 'dos', 'tres', 'cuatro'], 'valor': [1, 2, 3, 4], 'rel': [0, 1, 2, 3]}

In [97]:
df = pd.DataFrame(dictionary)

In [98]:
df.columns, df.index

(Index(['numero', 'valor', 'rel'], dtype='object'),
 RangeIndex(start=0, stop=4, step=1))

In [99]:
df = pd.read_csv('bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [100]:
pd.read_json('hpcharactersdataraw_3d934e85-dfa4-42ec-8520-fadfbecae574.json', typ='Series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

In [101]:
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [102]:
df[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [103]:
df[['Name', 'Author', 'Year']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  Year  
0                    JJ Smith  2016  
1                Stephen King  2011  
2          Jordan B. Peterson  2018  
3               George Orwell  2017  
4    National Geographic Kids  2019  
..                        ...   ...  
545               Jeff Kinney  2019  
546               Jen Sincero  2016  
547               Jen Sincero  2017  
548               Jen Sincero  2018  
549               Jen Sincero  2019  

[550 rows x 3 columns]

In [104]:
df.loc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [105]:
df.loc[0:4, ['Name', 'Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [106]:
df.loc[:, ['Reviews']] * -1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [107]:
df.loc[:, ['Author']] == 'JJ Smith'

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

In [108]:
df.iloc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [109]:
df.iloc[:,0:3]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

In [110]:
df.iloc[1,3] * -1

-2052

Drop columns

In [111]:
df.drop('Genre', axis=1, inplace=True)
df.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year  
0                  JJ Smith          4.7    17350      8  2016  
1              Stephen King          4.6     2052     22  2011  
2        Jordan B. Peterson          4.7    18979     15  2018  
3             George Orwell          4.7    21424      6  2017  
4  National Geographic Kids          4.8     7665     12  2019

In [112]:
df

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[550 rows x 6 columns]

In [113]:
df = df.drop('Year', axis=1)
df.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  
0                  JJ Smith          4.7    17350      8  
1              Stephen King          4.6     2052     22  
2        Jordan B. Peterson          4.7    18979     15  
3             George Orwell          4.7    21424      6  
4  National Geographic Kids          4.8     7665     12

In [114]:
del df['Price']
df.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  
0                  JJ Smith          4.7    17350  
1              Stephen King          4.6     2052  
2        Jordan B. Peterson          4.7    18979  
3             George Orwell          4.7    21424  
4  National Geographic Kids          4.8     7665

Drop rows

In [115]:
df = pd.read_csv('bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')
df.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [116]:
df.drop(0, axis=0).head()

Name  \
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   
5      A Dance with Dragons (A Song of Ice and Fire)   

                     Author  User Rating  Reviews  Price  Year        Genre  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction  
5       George R. R. Martin          4.4    12643     11  2011      Fiction

In [117]:
df.drop([0, 1, 2], axis=0).head()

Name  \
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   
5      A Dance with Dragons (A Song of Ice and Fire)   
6  A Game of Thrones / A Clash of Kings / A Storm...   
7                     A Gentleman in Moscow: A Novel   

                     Author  User Rating  Reviews  Price  Year        Genre  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction  
5       George R. R. Martin          4.4    12643     11  2011      Fiction  
6       George R. R. Martin          4.7    19735     30  2014      Fiction  
7               Amor Towles          4.7    19699     15  2017      Fiction

In [118]:
df.drop(range(0, 10), axis=0).head()

Name             Author  \
10                          A Man Called Ove: A Novel    Fredrik Backman   
11  A Patriot's History of the United States: From...   Larry Schweikart   
12                            A Stolen Life: A Memoir      Jaycee Dugard   
13                   A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
14  Act Like a Lady, Think Like a Man: What Men Re...       Steve Harvey   

    User Rating  Reviews  Price  Year        Genre  
10          4.6    23848      8  2017      Fiction  
11          4.6      460      2  2010  Non Fiction  
12          4.6     4149     32  2011  Non Fiction  
13          4.5     5153      5  2018      Fiction  
14          4.6     5013     17  2009  Non Fiction

add columns

In [119]:
df.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [120]:
df['Nueva Columna'] = np.nan
df.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  \
0                  JJ Smith          4.7    17350      8  2016  Non Fiction   
1              Stephen King          4.6     2052     22  2011      Fiction   
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3             George Orwell          4.7    21424      6  2017      Fiction   
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction   

   Nueva Columna  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN

In [121]:
data = np.arange(0, df.shape[0])
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [122]:
df['Rango'] = data
df.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  \
0                  JJ Smith          4.7    17350      8  2016  Non Fiction   
1              Stephen King          4.6     2052     22  2011      Fiction   
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3             George Orwell          4.7    21424      6  2017      Fiction   
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction   

   Nueva Columna  Rango  
0            NaN      0  
1            NaN      1  
2            NaN      2  
3            NaN      3  
4            NaN      4

agregar rows

In [123]:
df.append(df)

/tmp/ipykernel_64574/443893503.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df)


Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva Columna  Rango  
0              NaN      0  
1              NaN      1  
2              NaN      2  
3              NaN      3  
4              NaN      4  
..             ...    ...  
545            NaN    545  
546            NaN    546  
547            NaN    547  
548            NaN    548  
549            NaN    549  

[1100 rows x 9 columns]

In [124]:
data = {
    'Col1': [1, 2, 3, np.nan],
    'Col2': [4, np.nan, 6, 7],
    'Col3': ['a', 'b', 'c', None]
}

In [125]:
df = pd.DataFrame(data)
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [126]:
df.isnull()

Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [127]:
df.isnull() * 1

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [128]:
df.fillna('Missing')

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [129]:
df.fillna(df.mean())

/tmp/ipykernel_64574/634187881.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())


Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [130]:
df.interpolate()

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [131]:
df.dropna()

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

In [132]:
df = pd.read_csv('bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')
df.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [133]:
mayor_2016 = df['Year'] > 2016

In [134]:
df[mayor_2016]

Name  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
7                 Amor Towles          4.7    19699     15  2017      Fiction  
8                 James Comey          4.7     5983      3  2018  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
544             R. J. Palacio          4.8    21625      9  2017      Fiction  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[150 rows x 7 columns]

In [135]:
df[(df['Genre'] == 'Fiction') & (df['Year'] > 2016)]

Name             Author  \
3                               1984 (Signet Classics)      George Orwell   
7                       A Gentleman in Moscow: A Novel        Amor Towles   
10                           A Man Called Ove: A Novel    Fredrik Backman   
13                    A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
40            Brown Bear, Brown Bear, What Do You See?    Bill Martin Jr.   
..                                                 ...                ...   
509                              To Kill a Mockingbird         Harper Lee   
529  What Should Danny Do? (The Power to Choose Ser...          Adir Levy   
534                            Where the Crawdads Sing        Delia Owens   
544                                             Wonder      R. J. Palacio   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)        Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
3            4.7    21424      6  2017  Fiction  
7            4.7    19699     15  2017  Fiction  
10           4.6    23848      8  2017  Fiction  
13           4.5     5153      5  2018  Fiction  
40           4.9    14344      5  2017  Fiction  
..           ...      ...    ...   ...      ...  
509          4.8    26234      7  2019  Fiction  
529          4.8     8170     13  2019  Fiction  
534          4.8    87841     15  2019  Fiction  
544          4.8    21625      9  2017  Fiction  
545          4.9     9413      8  2019  Fiction  

[65 rows x 7 columns]

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [137]:
df.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [138]:
df.tail()

Name       Author  \
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)  Jeff Kinney   
546  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
547  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
545          4.9     9413      8  2019      Fiction  
546          4.7    14331      8  2016  Non Fiction  
547          4.7    14331      8  2017  Non Fiction  
548          4.7    14331      8  2018  Non Fiction  
549          4.7    14331      8  2019  Non Fiction

In [139]:
df.memory_usage(deep=True)

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

In [140]:
df['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [141]:
df = df.append(df)
df

/tmp/ipykernel_64574/3259320986.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df)


Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[1100 rows x 7 columns]

In [142]:
df.drop_duplicates()

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [143]:
df.sort_values('Year')

Name               Author  \
331  The 7 Habits of Highly Effective People: Power...     Stephen R. Covey   
91   Eat This Not That! Supermarket Survival Guide:...      David Zinczenko   
387         The Girl Who Played with Fire (Millennium)        Stieg Larsson   
388  The Girl with the Dragon Tattoo (Millennium Se...        Stieg Larsson   
364                       The Elegance of the Hedgehog       Muriel Barbery   
..                                                 ...                  ...   
128  Girl, Stop Apologizing: A Shame-Free Plan for ...        Rachel Hollis   
130  Girl, Wash Your Face: Stop Believing the Lies ...        Rachel Hollis   
138  Good Days Start With Gratitude: A 52 Week Guid...  Pretty Simple Press   
74   Difficult Riddles For Smart Kids: 300 Difficul...        M Prefontaine   
549  You Are a Badass: How to Stop Doubting Your Gr...          Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
331          4.6     9325     24  2009  Non Fiction  
91           4.5      720      1  2009  Non Fiction  
387          4.7     7251     16  2009      Fiction  
388          4.4    10559      2  2009      Fiction  
364          4.0     1859     11  2009      Fiction  
..           ...      ...    ...   ...          ...  
128          4.6     7660     12  2019  Non Fiction  
130          4.6    22288     12  2019  Non Fiction  
138          4.6    10141      6  2019  Non Fiction  
74           4.6     7955      5  2019  Non Fiction  
549          4.7    14331      8  2019  Non Fiction  

[1100 rows x 7 columns]

In [144]:
df.groupby('Author').count()

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               4            4        4      4     4      4
Adam Gasiewski                 2            2        2      2     2      2
Adam Mansbach                  2            2        2      2     2      2
Adir Levy                      2            2        2      2     2      2
Admiral William H. McRaven     2            2        2      2     2      2
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                6            6        6      6     6      6
William Davis                  4            4        4      4     4      4
William P. Young               4            4        4      4     4      4
Wizards RPG Team               6            6        6      6     6      6
Zhi Gang Sha                   4            4        4      4     4      4

[248 rows x 6 columns]

In [145]:
df.groupby('Author').sum()

User Rating  Reviews  Price   Year
Author                                                        
Abraham Verghese                   18.4    19464     44   8042
Adam Gasiewski                      8.8     6226     12   4034
Adam Mansbach                       9.6    19136     18   4022
Adir Levy                           9.6    16340     26   4038
Admiral William H. McRaven          9.4    20398     22   4034
...                                 ...      ...    ...    ...
Walter Isaacson                    27.4    37336    122  12080
William Davis                      17.6    29988     24   8050
William P. Young                   18.4    78880     32   8052
Wizards RPG Team                   28.8   101940    162  12108
Zhi Gang Sha                       18.4      514     46   8044

[248 rows x 4 columns]

In [146]:
df.groupby('Author').sum().loc['William Davis']

User Rating       17.6
Reviews        29988.0
Price             24.0
Year            8050.0
Name: William Davis, dtype: float64

In [147]:
df.groupby('Author').sum().reset_index()

Author  User Rating  Reviews  Price   Year
0              Abraham Verghese         18.4    19464     44   8042
1                Adam Gasiewski          8.8     6226     12   4034
2                 Adam Mansbach          9.6    19136     18   4022
3                     Adir Levy          9.6    16340     26   4038
4    Admiral William H. McRaven          9.4    20398     22   4034
..                          ...          ...      ...    ...    ...
243             Walter Isaacson         27.4    37336    122  12080
244               William Davis         17.6    29988     24   8050
245            William P. Young         18.4    78880     32   8052
246            Wizards RPG Team         28.8   101940    162  12108
247                Zhi Gang Sha         18.4      514     46   8044

[248 rows x 5 columns]

In [148]:
df.groupby('Author').agg(['min', 'max'])

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre               
                             max          min          max  
Author                                                      
Abraham Verghese            2011      Fiction      Fiction  
Adam Gasiewski              2017  Non Fiction  Non Fiction  
Adam Mansbach               2011      Fiction      Fiction  
Adir Levy                   2019      Fiction      Fiction  
Admiral William H. McRaven  2017  Non Fiction  Non Fiction  
...                          ...          ...          ...  
Walter Isaacson             2017  Non Fiction  Non Fiction  
William Davis               2013  Non Fiction  Non Fiction  
William P. Young            2017      F

In [149]:
df.groupby('Author').agg({'Reviews': ['min', 'max'], 'User Rating': 'sum'})

Reviews        User Rating
                               min    max         sum
Author                                               
Abraham Verghese              4866   4866        18.4
Adam Gasiewski                3113   3113         8.8
Adam Mansbach                 9568   9568         9.6
Adir Levy                     8170   8170         9.6
Admiral William H. McRaven   10199  10199         9.4
...                            ...    ...         ...
Walter Isaacson               3014   7827        27.4
William Davis                 7497   7497        17.6
William P. Young             19720  19720        18.4
Wizards RPG Team             16990  16990        28.8
Zhi Gang Sha                    37    220        18.4

[248 rows x 3 columns]

In [150]:
df.groupby(['Author', 'Year']).count()

Name  User Rating  Reviews  Price  Genre
Author           Year                                          
Abraham Verghese 2010     2            2        2      2      2
                 2011     2            2        2      2      2
Adam Gasiewski   2017     2            2        2      2      2
Adam Mansbach    2011     2            2        2      2      2
Adir Levy        2019     2            2        2      2      2
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     2            2        2      2      2
                 2018     2            2        2      2      2
                 2019     2            2        2      2      2
Zhi Gang Sha     2009     2            2        2      2      2
                 2013     2            2        2      2      2

[493 rows x 5 columns]

Merge, Join, Concat

In [153]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3'],
})
df2 = pd.DataFrame({
    'A': ['A4', 'A5', 'A6', 'A7'],
    'B': ['B4', 'B5', 'B6', 'B7'],
    'C': ['C4', 'C5', 'C6', 'C7'],
    'D': ['D4', 'D5', 'D6', 'D7'],
})

In [155]:
pd.concat([df1, df2], ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [156]:
pd.concat([df1, df2], axis=1)

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

In [157]:
izq = pd.DataFrame({
    'key': ['k0', 'k1', 'k2', 'k3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3'],
})

der = pd.DataFrame({
    'key': ['k0', 'k1', 'k2', 'k3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3'],
})

In [158]:
izq.merge(der)

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [159]:
izq = pd.DataFrame({
    'key': ['k0', 'k1', 'k2', 'k3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3'],
})

der = pd.DataFrame({
    'key_2': ['k0', 'k1', 'k2', 'k3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3'],
})

In [161]:
izq.merge(der,left_on='key', right_on='key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2
3  k3  A3  B3    k3  C3  D3

In [162]:
izq = pd.DataFrame({
    'A': ['A0','A1','A2'],
    'B':['B0','B1','B2']},
    index=['k0','k1','k2']
)

der =pd.DataFrame({
    'C': ['C0','C1','C2'],
    'D':['D0','D1','D2']},
    index=['k0','k2','k3']
)

In [163]:
izq.join(der)

A   B    C    D
k0  A0  B0   C0   D0
k1  A1  B1  NaN  NaN
k2  A2  B2   C1   D1

In [164]:
izq.join(der, how='outer')

A    B    C    D
k0   A0   B0   C0   D0
k1   A1   B1  NaN  NaN
k2   A2   B2   C1   D1
k3  NaN  NaN   C2   D2

In [166]:
df_books = pd.read_csv('bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv',sep=',',header=0)
df_books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [167]:
df_books.pivot_table(index='Author', columns='Genre', values='User Rating')

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

In [168]:
df_books.pivot_table(index='Genre',columns='Year', values='User Rating',aggfunc='sum')

Year          2009   2010   2011   2012   2013   2014   2015   2016   2017  \
Genre                                                                        
Fiction      110.2   92.3   97.0   94.4  109.1  134.3   79.1   89.6  113.7   
Non Fiction  119.0  135.6  130.9  132.2  118.6   96.8  153.3  144.3  119.3   

Year          2018   2019  
Genre                      
Fiction       99.5   96.4  
Non Fiction  133.9  140.6

In [169]:
df_books[['Name','Genre']].head(5)

Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

In [170]:
df_books[['Name','Genre']].head(5).melt()

variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

In [171]:
df_books.melt(id_vars='Year',value_vars='Genre')

Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
545  2019    Genre      Fiction
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction

[550 rows x 3 columns]

In [173]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])