In [3]:
import numpy as np
import pandas as pd

Array numpy

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
type(arr)

numpy.ndarray

In [8]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr[0]

1

In [12]:
arr[0] + arr[5]

7

In [14]:
matriz[0,2]

3

In [15]:
arr[0:3]

array([1, 2, 3])

In [16]:
arr[::3]

array([1, 4, 7])

In [18]:
arr[-1]

9

In [19]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

tipos de datos

In [30]:
arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int64')

In [31]:
arr

array([1, 2, 3, 4])

In [32]:
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

In [27]:
arr = np.array([1, 2, 3, 4], dtype='float64')
arr.dtype

dtype('float64')

In [36]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True])

In [37]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3'], dtype='|S21')

In [38]:
arr = np.array(['0', '1', '2', '3'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3], dtype=int8)

Dimensiones

In [39]:
scalar = np.array(42)
print(scalar)
print(scalar.ndim)

42
0


In [40]:
vector = np.array([1, 2, 3])
print(vector)
print(vector.ndim)

[1 2 3]
1


In [41]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
print(matriz.ndim)

[[1 2 3]
 [4 5 6]]
2


In [42]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tensor)
print(tensor.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [44]:
vector = np.array([1, 2, 3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [47]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
print(expand.ndim)

[[1 2 3]]
2


In [48]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 10
